---
kind: ConfigMap
apiVersion: v1
metadata:
  name: api-gateway
  namespace: spring-petclinic
data:
  application.yaml: |-
    # Server
    server:
      shutdown: graceful
      lifecycle:
        timeout-per-shutdown-phase: 15
      port: 8080
      compression:
        enabled: true
        mime-types: application/json,text/css,application/javascript
        min-response-size: 2048

    # Logging
    logging.level.org.springframework: INFO

    # Metrics
    management:
      endpoint:
        health:
          probes:
            enabled: true
        info:
          enabled: true
        restart:
          enabled: true
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true
        restart:
          enabled: true
        metrics:
          enabled: true
        prometheus:
          enabled: true
      endpoints:
        web:
          exposure:
            include: '*'
      metrics:
        export:
          prometheus:
            enabled: true
          wavefront:
            enabled: false
            
    customers-service-id: http://customers-service.spring-petclinic.svc.cluster.local:8080
    visits-service-id: http://vists-service.spring-petclinic.svc.cluster.local:8080
    
    # Spring
    spring:
      datasource:
        schema: classpath*:db/mysql-k8s/schema.sql
        data: classpath*:db/mysql-k8s/data.sql
        platform: mysql
        initialization-mode: always
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: none
          generate-ddl: false
      #sleuth:
      #  sampler:
      #    probability: 1.0
      #  config:
      #    # Allow the microservices to override the remote properties with their own System properties or config file
      #    allow-override: true
      #    # Override configuration with any local property source
      #    override-none: true
      messages:
        basename: messages/messages
      cloud:
        kubernetes:
          discovery:
            enabled: true
        loadbalancer:
          ribbon:
            enabled: false
        gateway:
          x-forwarded:  
            enabled: true 
            for-enabled: true 
            proto-enabled: true 
            host-append: false  
            port-append: false  
            proto-append: false
          routes:
            - id: vets-service
              uri: http://vets-service.spring-petclinic.svc.cluster.local:8080
              predicates:
                - Path=/api/vet/**
              filters:
                - StripPrefix=2
            - id: visits-service
              uri: http://visits-service.spring-petclinic.svc.cluster.local:8080
              predicates:
                - Path=/api/visit/**
              filters:
                - StripPrefix=2
            - id: customers-service
              uri: http://customers-service.spring-petclinic.svc.cluster.local:8080
              predicates:
                - Path=/api/customer/**
              filters:
                - StripPrefix=2