---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: customers-service
  name: customers-service
  namespace: spring-petclinic
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app: customers-service
status:
  loadBalancer: {}
