---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vets-service
  labels:
    app: vets-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: vets-service
  namespaceSelector:
    any: true
  endpoints:
  - port: web
    path: /actuator/prometheus
    interval: 10s